# Generated by Django 5.1.2 on 2024-11-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='enlace_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
