# Generated by Django 5.1.3 on 2024-11-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_proyecto_enlace_github_proyecto_tecnologias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                ("fecha_publicacion", models.DateField(auto_now_add=True)),
                ("autor", models.CharField(default="Luis Viteri", max_length=100)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="blogs/"),
                ),
                ("categorias", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Proyecto",
        ),
    ]
